FROM ubuntu:16.04

COPY /file/jonathonf-ubuntu-firefox-esr-xenial.list /etc/apt/sources.list.d/jonathonf-ubuntu-firefox-esr-xenial.list
RUN apt-get update
RUN apt-get install -y --allow-unauthenticated software-properties-common \
  firefox-esr \
  openssh-server \
  xauth \
  language-pack-en-base \
  curl
# Java install
RUN add-apt-repository ppa:webupd8team/java
RUN apt-get update && \
  echo oracle-java7-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections && \
    apt-get install -y oracle-java8-installer && \
    apt-get clean

# Setup SSH
RUN mkdir /var/run/sshd
RUN echo 'root:screencast' | chpasswd
RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd
ENV NOTVISIBLE "in users profile"
RUN echo "export VISIBLE=now" >> /etc/profile

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]
