version: '3'

services:
  firefox:
    container_name: firefoxesr
    build:
      context: .
    restart: always
    ports:
      - "2222:22"
    networks:
      app_net:
        ipv4_address: 10.1.0.25

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 10.1.0.0/24
