FROM ubuntu:16.04

COPY /file/jonathonf-ubuntu-firefox-esr-xenial.list /etc/apt/sources.list.d/jonathonf-ubuntu-firefox-esr-xenial.list
RUN apt-get update
RUN apt-get install -y language-pack-en-base
RUN apt-get install -y --allow-unauthenticated firefox-esr openssh-server xauth
RUN mkdir /var/run/sshd
RUN echo 'root:screencast' | chpasswd
RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd
ENV NOTVISIBLE "in users profile"
RUN echo "export VISIBLE=now" >> /etc/profile

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]
